@startuml
'https://plantuml.com/class-diagram

interface OnClickListener{
    + void onClick()

}

class Button{
    - List listeners
    + void attach(OnClickListener observer)
    + void click()
}

class Activity{
    - int soLanClick
    + Activity()
    + void onClick()
}

Button--> OnClickListener
Activity ..|> OnClickListener
Activity--> Button

@enduml